controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

default:
    path: /
    controller: App\Controller\DefaultController::index

dashboard:
    path: /admin
    controller: App\Controller\DashboardController::base

login:
        path: /login
        controller: App\Controller\SecurityController::login


apropos:
    path: /apropos
    controller: App\Controller\aproposController::apropos

Localisation:
    path: /localisation
    controller: App\Controller\localisationController::Localisation

contact_form:
    path: /contact_form
    controller: App\Controller\ContactFormController::contact_form


nous_connaitre:
    path: /nous_connaitre
    controller: App\Controller\NousConnaitreController::nous_connaitre

tce:
    path: /tce
    controller: App\Controller\tceController::tce

cet:
    path: /cet
    controller: App\Controller\CetController::cet

ces:
    path: /ces
    controller: App\Controller\CesController::ces


Maçonnerie :
    path: /Maçonnerie
    controller: App\Controller\MaconnerieContollerController::Maçonnerie

revetementdesolemur :
    path: /revetementdesolemur
    controller: App\Controller\RevetementdesolemurController ::revetementdesolemur
    

carrelage :
    path: /carrelage
    controller: App\Controller\CarrelageController::carrelage


paterie :
    path: /paterie
    controller: App\Controller\PaterieController::paterie


peinture :
    path: /peinture
    controller: App\Controller\PaterieController::peinture

plomberie :
    path: /plomberie
    controller: App\Controller\PlomberieController::index



menuiseriebois :
    path: /menuiseriebois
    controller: App\Controller\menuiserieboisController::index

menuiseriealimunium:
    path: /menuiseriealimunium
    controller: App\Controller\MenuiseriealimuniumController::menuiseriealimunium

climatisation:
    path: /climatisation 
    controller: App\Controller\ClimatisationController::climatisation 

asenceurs:
    path: /asenceurs 
    controller: App\Controller\AsenceursController::asenceurs 