controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

default:
    path: /
    controller: App\Controller\DefaultController::index

dashboard:
    path: /admin
    controller: App\Controller\DashboardController::index

login:
        path: /login
        controller: App\Controller\SecurityController::login



